version: "3.8"

services:

  fuji:
    container_name: fuji
    build:
      context: ./fuji        
      dockerfile: Dockerfile 
    ports:
      - "1071:1071"
    restart: unless-stopped

  app:
    container_name: sustainalyze_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fuji
    env_file:
      - .env
    environment:
      FUJI_HOST: http://fuji:1071
    restart: unless-stopped
